### ISSUE TITLE
error when trying to schedule job in past

### ISSUE THREAD

**Issue by tejasmanohar** [tejasmanohar/node-schedule#184] opened 2015-08-31 05:57 UTC
this is something we should add to the next version rather than just not scheduling the job entirely... not in this version because that'd be a breaking change

**Comment by santigimeno** [comment] 2015-08-31 08:48
Duplicate of https://github.com/tejasmanohar/node-schedule/issues/157

**Closed** 2015-08-31 16:21 UTC
